<?xml version="1.0" encoding="utf-8" ?>
<!DOCTYPE blocks [
        <!ELEMENT blocks (block)*>
        <!ELEMENT block (src|href_img|song_name|group|group_src)*>
        <!ELEMENT src (#PCDATA)>
        <!ELEMENT href_img (#PCDATA)>
        <!ELEMENT song_name (#PCDATA)>
        <!ELEMENT group (#PCDATA)>
        <!ELEMENT group_src (#PCDATA)>
        ]>
<blocks>
    <block>
        <src>chords.html</src>
        <href_img>content/images/groups/egor.png</href_img>
        <song_name>Далеко бежит дорога (Впереди веселья много)</song_name>
        <group>Гражданская Оборона</group>
        <group_src>perfomer_page.html</group_src>
    </block>
    <block>
        <src>vesna.html</src>
        <href_img>content/images/groups/kino.png</href_img>
        <song_name>Весна</song_name>
        <group>Кино</group>
        <group_src>kino.html</group_src>
    </block>
    <block>
        <src>dlya_yanki.html</src>
        <href_img>content/images/groups/egor.png</href_img>
        <song_name>Плюшевый мишутка (песенка для Янки)</song_name>
        <group>Гражданская Оборона</group>
        <group_src>perfomer_page.html</group_src>
    </block>
</blocks>